# .github/workflows/production.yml
name: Vercel Production Deployment

# Run on push to main OR PRs targeting main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN:     ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' 
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install project dependencies
      working-directory: frontend
      run: npm install

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Vercel env info
      working-directory: frontend
      run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

    - name: Build project
      working-directory: frontend
      run: vercel build --prod --token=$VERCEL_TOKEN

    - name: Deploy to Vercel
      working-directory: frontend
      run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN